FROM python:3.7

LABEL maintainer=osozdemirorcun@gmail.com

WORKDIR /usr/src/app

COPY ./orchestrator/speech_service/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./utils/common_utils ./common_utils
COPY ./config_ ./config_

COPY ./orchestrator/speech_service ./
